name: pix2seq
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - libedit=3.1.20221030
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.0
  - readline=7.0
  - setuptools=66.0.0
  - sqlite=3.33.0
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accelerate==0.19.0
      - albumentations==1.2.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - cycler==0.11.0
      - einops==0.6.1
      - ema-pytorch==0.2.3
      - filelock==3.12.0
      - fonttools==4.39.4
      - fsspec==2023.5.0
      - huggingface-hub==0.14.1
      - idna==3.4
      - imageio==2.28.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - map-boxes==1.0.5
      - matplotlib==3.5.1
      - networkx==3.1
      - numpy==1.21.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - opencv-python-headless==4.7.0.72
      - packaging==23.1
      - pandas==1.3.5
      - pillow==9.5.0
      - psutil==5.9.5
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qudida==0.0.4
      - regex==2023.5.5
      - requests==2.30.0
      - scikit-image==0.20.0
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - six==1.16.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - timm==0.6.7
      - tokenizers==0.12.1
      - torch==1.13.1
      - torchinfo==1.8.0
      - torchvision==0.14.1
      - tqdm==4.62.3
      - transformers==4.21.1
      - typing-extensions==4.5.0
      - urllib3==2.0.2
